# Generated by Django 3.2.6 on 2021-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(default='General', max_length=228),
        ),
    ]
