# Generated by Django 3.2.6 on 2021-10-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0003_feed_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=228)),
                ('link', models.CharField(max_length=228)),
                ('category', models.CharField(max_length=228)),
                ('img', models.CharField(max_length=228)),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='category',
        ),
    ]
