# Generated by Django 3.2.6 on 2021-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0004_auto_20211017_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
