# Generated by Django 3.2.6 on 2021-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0005_auto_20211017_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
