# Generated by Django 3.2.6 on 2021-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0008_news_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner', models.TextField(blank=True, null=True)),
                ('bill_board', models.TextField(blank=True, null=True)),
                ('category_one', models.TextField(blank=True, null=True)),
                ('category_two', models.TextField(blank=True, null=True)),
                ('category_three', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
