# Generated by Django 3.2.6 on 2021-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0009_adscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscode',
            name='access_name',
            field=models.CharField(default='admin', max_length=32),
        ),
    ]
