# Generated by Django 3.2.6 on 2021-10-29 13:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0010_adscode_access_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRVINews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=228)),
                ('link', models.CharField(max_length=228)),
                ('category', models.CharField(blank=True, max_length=228, null=True)),
                ('img', models.CharField(max_length=228)),
                ('pub_date', models.CharField(blank=True, max_length=228, null=True)),
                ('source', models.CharField(blank=True, max_length=228, null=True)),
                ('news_context', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
