# Generated by Django 3.2.6 on 2021-10-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0011_prvinews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prvinews',
            name='link',
        ),
    ]
