# Generated by Django 3.2.6 on 2021-11-02 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0012_remove_prvinews_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_one', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('section_two', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('section_three', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('access_name', ckeditor.fields.RichTextField(default='admin')),
            ],
        ),
    ]
