# Generated by Django 3.2.6 on 2021-11-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0013_footerhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerhtml',
            name='access_name',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
