# Generated by Django 3.2.6 on 2021-11-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0015_auto_20211103_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscode',
            name='sidebarAD',
            field=models.TextField(blank=True, null=True),
        ),
    ]
