# Generated by Django 3.2.6 on 2021-11-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0017_auto_20211111_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscode',
            name='home_sideAD',
        ),
        migrations.AddField(
            model_name='adscode',
            name='biznisSideAD',
            field=models.TextField(blank=True, help_text='Home Page Biznis Side News, Size: 300x250', null=True),
        ),
        migrations.AddField(
            model_name='adscode',
            name='biznisSideBar',
            field=models.TextField(blank=True, help_text='Home Page Ostale Biznis Side Bar, Size: 728x90', null=True),
        ),
        migrations.AddField(
            model_name='adscode',
            name='sportSideBar',
            field=models.TextField(blank=True, help_text='Home Page Ostale Sport Side Bar, Size: 728x90', null=True),
        ),
        migrations.AddField(
            model_name='adscode',
            name='techSideAD',
            field=models.TextField(blank=True, help_text='Home Page Tech Side News, Size: 300x250', null=True),
        ),
        migrations.AddField(
            model_name='adscode',
            name='topSideAD',
            field=models.TextField(blank=True, help_text='Home Page Top Section Side News, Size: 300x250', null=True),
        ),
    ]
