# Generated by Django 3.2.6 on 2021-11-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0015_auto_20211103_2050'),
        ('rssReader', '0018_auto_20211111_0827'),
    ]

    operations = [
    ]
