# Generated by Django 3.2.6 on 2021-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0019_merge_0015_auto_20211103_2050_0018_auto_20211111_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscode',
            name='home_sideAD',
        ),
        migrations.AlterField(
            model_name='adscode',
            name='bill_board',
            field=models.TextField(blank=True, help_text='Between Top and Biznis', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='biznisSideBar',
            field=models.TextField(blank=True, help_text='Home Page Ostale Biznis Side Bar, Size: 300x600', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='category_one',
            field=models.TextField(blank=True, help_text='above Ostale Biznis Size : 728x90', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='category_sideAD',
            field=models.TextField(blank=True, help_text='Category Side AD, Size: 300x250', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='category_two',
            field=models.TextField(blank=True, help_text='above Ostale Sport Size : 728x90', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='sidebarAD',
            field=models.TextField(blank=True, help_text='Category & Source Page Side Bar, Size: 300x600', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='source_sideAD',
            field=models.TextField(blank=True, help_text='Source Side AD, Size: 300x250', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='sportSideBar',
            field=models.TextField(blank=True, help_text='Home Page Ostale Sport Side Bar, Size: 300x600', null=True),
        ),
        migrations.AlterField(
            model_name='adscode',
            name='top_banner',
            field=models.TextField(blank=True, help_text='Scroll Top Banner', null=True),
        ),
    ]
