# Generated by Django 3.2.6 on 2021-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0020_auto_20211111_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscode',
            name='biznisSideBar',
        ),
        migrations.AddField(
            model_name='adscode',
            name='vijestiSideBar',
            field=models.TextField(blank=True, help_text='Home Page Ostale Vijesti Side Bar, Size: 300x600', null=True),
        ),
    ]
